import { Account, FraudRing, HoldActionResponse, RiskScoreResponse, Transaction, OfficerProfile } from "@/types/account";

// Available officer profiles for the navbar switcher
export const OFFICER_PROFILES: OfficerProfile[] = [
  {
    id: "OFF_MP_2026",
    name: "Inspector Vikram Sharma",
    badge: "MP-CYBER-884",
    agency: "MP Cyber Crime Cell, Bhopal",
    jurisdiction: "Madhya Pradesh Special Task Force",
  },
  {
    id: "OFF_DEL_2026",
    name: "ACP Rajesh Malhotra",
    badge: "DEL-IFSO-102",
    agency: "Delhi Police IFSO (Special Cell)",
    jurisdiction: "National Capital Region",
  },
  {
    id: "OFF_MH_2026",
    name: "Sr. PI Ananya Deshmukh",
    badge: "MH-CYBER-509",
    agency: "Maharashtra Cyber Headquarters",
    jurisdiction: "Western Zone Financial Intelligence",
  },
  {
    id: "OFF_CBI_2026",
    name: "Superintendent K. S. Rao",
    badge: "CBI-BFIO-044",
    agency: "Banking Fraud & Cyber Security Division",
    jurisdiction: "Pan-India Federal Liaison",
  },
];

// Mock Accounts Dataset
export const MOCK_ACCOUNTS: Account[] = [
  {
    account_id: "ACC_00042",
    holder_name: "Rameshwar Prasad Verma",
    bank_name: "SBI",
    account_age_days: 14,
    kyc_level: "basic",
    status: "flagged",
    persona: "burst_mule",
    upi_vpa: "ramesh.verma91@oksbi",
    risk_score: 94,
    ring_id: "RING_FO_01",
    created_at: "2026-09-15T04:20:00Z",
  },
  {
    account_id: "ACC_00043",
    holder_name: "Amit Kumar Jaiswal",
    bank_name: "HDFC",
    account_age_days: 22,
    kyc_level: "basic",
    status: "flagged",
    persona: "mule_funnel",
    upi_vpa: "amit.j99@okhdfcbank",
    risk_score: 89,
    ring_id: "RING_FO_01",
    created_at: "2026-09-07T08:12:00Z",
  },
  {
    account_id: "ACC_00044",
    holder_name: "Sunita Devi",
    bank_name: "PNB",
    account_age_days: 18,
    kyc_level: "basic",
    status: "on_hold",
    persona: "burst_mule",
    upi_vpa: "sunita.pay88@okpnb",
    risk_score: 91,
    ring_id: "RING_FO_01",
    active_hold_id: "ACT_HOLD_9001",
    created_at: "2026-09-11T11:45:00Z",
  },
  {
    account_id: "ACC_00108",
    holder_name: "Karan Johar Enterprises Ltd",
    bank_name: "ICICI",
    account_age_days: 45,
    kyc_level: "full",
    status: "flagged",
    persona: "mule_funnel",
    upi_vpa: "karan.trade@icici",
    risk_score: 96,
    ring_id: "RING_CL_02",
    created_at: "2026-08-15T10:00:00Z",
  },
  {
    account_id: "ACC_00109",
    holder_name: "Neelam FinServe Direct",
    bank_name: "Axis",
    account_age_days: 41,
    kyc_level: "full",
    status: "flagged",
    persona: "mule_funnel",
    upi_vpa: "neelam.fin@okaxis",
    risk_score: 93,
    ring_id: "RING_CL_02",
    created_at: "2026-08-19T14:30:00Z",
  },
  {
    account_id: "ACC_00110",
    holder_name: "Shyam Sundar Trading",
    bank_name: "Kotak",
    account_age_days: 38,
    kyc_level: "basic",
    status: "on_hold",
    persona: "mule_funnel",
    upi_vpa: "shyam.trade@kotak",
    risk_score: 95,
    ring_id: "RING_CL_02",
    active_hold_id: "ACT_HOLD_9002",
    created_at: "2026-08-22T09:15:00Z",
  },
  {
    account_id: "ACC_00215",
    holder_name: "Farhan Akhtar",
    bank_name: "SBI",
    account_age_days: 8,
    kyc_level: "basic",
    status: "flagged",
    persona: "burst_mule",
    upi_vpa: "farhan.akhtar9@oksbi",
    risk_score: 97,
    ring_id: "RING_DF_03",
    created_at: "2026-09-21T03:10:00Z",
  },
  {
    account_id: "ACC_00216",
    holder_name: "Vikas Dubey",
    bank_name: "HDFC",
    account_age_days: 8,
    kyc_level: "basic",
    status: "flagged",
    persona: "burst_mule",
    upi_vpa: "vikas.dubey99@okhdfcbank",
    risk_score: 96,
    ring_id: "RING_DF_03",
    created_at: "2026-09-21T03:14:00Z",
  },
  {
    account_id: "ACC_00217",
    holder_name: "Pooja Hegde",
    bank_name: "ICICI",
    account_age_days: 9,
    kyc_level: "basic",
    status: "on_hold",
    persona: "burst_mule",
    upi_vpa: "pooja.h88@icici",
    risk_score: 95,
    ring_id: "RING_DF_03",
    active_hold_id: "ACT_HOLD_9003",
    created_at: "2026-09-20T16:40:00Z",
  },
  {
    account_id: "ACC_00330",
    holder_name: "Golden Gateway Logistics",
    bank_name: "Axis",
    account_age_days: 28,
    kyc_level: "full",
    status: "flagged",
    persona: "mule_funnel",
    upi_vpa: "gateway.cash@axis",
    risk_score: 92,
    ring_id: "RING_FC_05",
    created_at: "2026-09-01T12:00:00Z",
  },
  {
    account_id: "ACC_00331",
    holder_name: "Dinesh Chandila",
    bank_name: "PNB",
    account_age_days: 25,
    kyc_level: "basic",
    status: "flagged",
    persona: "burst_mule",
    upi_vpa: "dinesh.c44@pnb",
    risk_score: 87,
    ring_id: "RING_FC_05",
    created_at: "2026-09-04T07:22:00Z",
  },
  {
    account_id: "ACC_00411",
    holder_name: "Deepak Choudhary",
    bank_name: "Kotak",
    account_age_days: 12,
    kyc_level: "basic",
    status: "flagged",
    persona: "burst_mule",
    upi_vpa: "deepak.c12@kotak",
    risk_score: 93,
    ring_id: "RING_BM_04",
    created_at: "2026-09-17T01:30:00Z",
  },
  {
    account_id: "ACC_00078",
    holder_name: "Sneha Mukherjee",
    bank_name: "HDFC",
    account_age_days: 140,
    kyc_level: "full",
    status: "clear",
    persona: "student",
    upi_vpa: "sneha.m@okhdfcbank",
    risk_score: 52,
    created_at: "2026-05-12T14:10:00Z",
  },
  {
    account_id: "ACC_00155",
    holder_name: "Sharma Kirana Store",
    bank_name: "SBI",
    account_age_days: 430,
    kyc_level: "full",
    status: "clear",
    persona: "merchant",
    upi_vpa: "sharmakiranabpl@oksbi",
    risk_score: 48,
    created_at: "2025-07-26T09:00:00Z",
  },
  {
    account_id: "ACC_00001",
    holder_name: "Pradeep Joshi",
    bank_name: "SBI",
    account_age_days: 720,
    kyc_level: "full",
    status: "clear",
    persona: "salaried",
    upi_vpa: "pradeep.joshi@oksbi",
    risk_score: 12,
    created_at: "2024-10-10T08:00:00Z",
  },
  {
    account_id: "ACC_00002",
    holder_name: "Anjali Gupta",
    bank_name: "ICICI",
    account_age_days: 890,
    kyc_level: "full",
    status: "clear",
    persona: "salaried",
    upi_vpa: "anjali.g@icici",
    risk_score: 8,
    created_at: "2024-04-22T10:30:00Z",
  },
  {
    account_id: "ACC_00003",
    holder_name: "Rajeshwar Rao",
    bank_name: "Axis",
    account_age_days: 540,
    kyc_level: "full",
    status: "clear",
    persona: "family",
    upi_vpa: "rajeshwar.rao@axis",
    risk_score: 18,
    created_at: "2025-04-08T15:20:00Z",
  },
  {
    account_id: "ACC_00004",
    holder_name: "Mohammad Tariq",
    bank_name: "Kotak",
    account_age_days: 310,
    kyc_level: "full",
    status: "clear",
    persona: "student",
    upi_vpa: "tariq.m98@kotak",
    risk_score: 24,
    created_at: "2025-11-23T16:45:00Z",
  },
  {
    account_id: "ACC_00005",
    holder_name: "Gopal Krishna Traders",
    bank_name: "PNB",
    account_age_days: 610,
    kyc_level: "full",
    status: "clear",
    persona: "merchant",
    upi_vpa: "gopaltraders@pnb",
    risk_score: 31,
    created_at: "2025-01-30T11:00:00Z",
  },
  {
    account_id: "ACC_00006",
    holder_name: "Kavita R. Nair",
    bank_name: "HDFC",
    account_age_days: 1050,
    kyc_level: "full",
    status: "clear",
    persona: "dormant",
    upi_vpa: "kavita.nair@hdfcbank",
    risk_score: 5,
    created_at: "2023-11-14T09:15:00Z",
  },
];

// Mock Transactions
export const MOCK_TRANSACTIONS: Record<string, Transaction[]> = {
  ACC_00042: [
    {
      txn_id: "TXN_7749102",
      sender_account_id: "ACC_00042",
      receiver_account_id: "ACC_00043",
      amount: 9950,
      channel: "UPI",
      device_id: "DEV_IN_774",
      timestamp: "2026-09-29T02:14:22Z",
      is_flagged: true,
      tag: "Structuring (< ₹10k)",
    },
    {
      txn_id: "TXN_7749103",
      sender_account_id: "ACC_00042",
      receiver_account_id: "ACC_00044",
      amount: 9800,
      channel: "UPI",
      device_id: "DEV_IN_774",
      timestamp: "2026-09-29T02:18:05Z",
      is_flagged: true,
      tag: "Structuring (< ₹10k)",
    },
    {
      txn_id: "TXN_7749089",
      sender_account_id: "EXT_VICTIM_9901",
      receiver_account_id: "ACC_00042",
      amount: 450000,
      channel: "IMPS",
      device_id: "DEV_UNKNOWN",
      timestamp: "2026-09-29T01:52:10Z",
      is_flagged: true,
      tag: "Sudden High Credit",
    },
    {
      txn_id: "TXN_7749105",
      sender_account_id: "ACC_00042",
      receiver_account_id: "ACC_00045",
      amount: 9900,
      channel: "UPI",
      device_id: "DEV_IN_774",
      timestamp: "2026-09-29T02:22:40Z",
      is_flagged: true,
      tag: "Structuring (< ₹10k)",
    },
    {
      txn_id: "TXN_7749108",
      sender_account_id: "ACC_00042",
      receiver_account_id: "ACC_00046",
      amount: 9750,
      channel: "UPI",
      device_id: "DEV_IN_774",
      timestamp: "2026-09-29T02:25:11Z",
      is_flagged: true,
      tag: "High Velocity Night Burst",
    },
    {
      txn_id: "TXN_7749112",
      sender_account_id: "ACC_00042",
      receiver_account_id: "ACC_00047",
      amount: 9900,
      channel: "UPI",
      device_id: "DEV_IN_774",
      timestamp: "2026-09-29T02:29:40Z",
      is_flagged: true,
      tag: "Structuring (< ₹10k)",
    },
  ],
  ACC_00108: [
    {
      txn_id: "TXN_8812001",
      sender_account_id: "ACC_00112",
      receiver_account_id: "ACC_00108",
      amount: 48500,
      channel: "IMPS",
      device_id: "DEV_CORP_01",
      timestamp: "2026-09-28T23:15:00Z",
      is_flagged: true,
      tag: "Cycle Completion Loop",
    },
    {
      txn_id: "TXN_8812002",
      sender_account_id: "ACC_00108",
      receiver_account_id: "ACC_00109",
      amount: 47000,
      channel: "UPI",
      device_id: "DEV_CORP_01",
      timestamp: "2026-09-28T23:45:00Z",
      is_flagged: true,
      tag: "Layering Forwarding",
    },
    {
      txn_id: "TXN_8812003",
      sender_account_id: "ACC_00108",
      receiver_account_id: "ACC_00110",
      amount: 35000,
      channel: "IMPS",
      device_id: "DEV_CORP_01",
      timestamp: "2026-09-29T00:30:00Z",
      is_flagged: true,
      tag: "Dwell Time < 30min",
    },
  ],
  ACC_00215: [
    {
      txn_id: "TXN_9931001",
      sender_account_id: "ACC_00215",
      receiver_account_id: "ACC_00991",
      amount: 9990,
      channel: "UPI",
      device_id: "DEV_FARM_9921",
      timestamp: "2026-09-29T03:12:00Z",
      is_flagged: true,
      tag: "Shared Device Fingerprint",
    },
    {
      txn_id: "TXN_9931002",
      sender_account_id: "ACC_00215",
      receiver_account_id: "ACC_00992",
      amount: 9850,
      channel: "UPI",
      device_id: "DEV_FARM_9921",
      timestamp: "2026-09-29T03:18:00Z",
      is_flagged: true,
      tag: "Night Shift 3 AM",
    },
    {
      txn_id: "TXN_9931003",
      sender_account_id: "ACC_00215",
      receiver_account_id: "ACC_00993",
      amount: 9920,
      channel: "UPI",
      device_id: "DEV_FARM_9921",
      timestamp: "2026-09-29T03:22:00Z",
      is_flagged: true,
      tag: "Structuring (< ₹10k)",
    },
  ],
  ACC_00001: [
    {
      txn_id: "TXN_1001",
      sender_account_id: "TCS_CORP_SALARY",
      receiver_account_id: "ACC_00001",
      amount: 68500,
      channel: "NEFT",
      device_id: "DEV_OFFICE_01",
      timestamp: "2026-09-01T09:30:00Z",
      is_flagged: false,
      tag: "Monthly Salary Credit",
    },
    {
      txn_id: "TXN_1002",
      sender_account_id: "ACC_00001",
      receiver_account_id: "SWIGGY_MERCHANT",
      amount: 420,
      channel: "UPI",
      device_id: "DEV_SAMSUNG_S23",
      timestamp: "2026-09-25T13:15:00Z",
      is_flagged: false,
      tag: "Food & Dining",
    },
    {
      txn_id: "TXN_1003",
      sender_account_id: "ACC_00001",
      receiver_account_id: "BESCOM_ELECTRICITY",
      amount: 1850,
      channel: "UPI",
      device_id: "DEV_SAMSUNG_S23",
      timestamp: "2026-09-18T18:40:00Z",
      is_flagged: false,
      tag: "Utility Bill",
    },
  ],
};

// Mock Risk Scores & SHAP Explanations
export const MOCK_RISK_SCORES: Record<string, RiskScoreResponse> = {
  ACC_00042: {
    account_id: "ACC_00042",
    score: 94,
    top_features: {
      band: "high",
      shap: [
        {
          feature: "pass_through_ratio",
          value: 0.98,
          direction: "increases_risk",
          contribution: 0.32,
          description: "forwards 98% of received money within 25 minutes",
        },
        {
          feature: "near_threshold_ratio",
          value: 0.85,
          direction: "increases_risk",
          contribution: 0.28,
          description: "85% of amounts are ₹9,000–₹9,999 (structuring pattern)",
        },
        {
          feature: "night_txn_ratio",
          value: 0.76,
          direction: "increases_risk",
          contribution: 0.21,
          description: "76% of transactions occur between 12am and 5am",
        },
        {
          feature: "fan_out",
          value: 14,
          direction: "increases_risk",
          contribution: 0.18,
          description: "disperses funds to 14 unique receivers rapidly",
        },
        {
          feature: "account_age_days",
          value: 14,
          direction: "increases_risk",
          contribution: 0.14,
          description: "new account created only 14 days ago",
        },
      ],
    },
    explanation_text:
      "CRITICAL FRAUD SUSPECT: Account ACC_00042 acts as a high-velocity fan-out dispersal node. Upon receiving a ₹4.5L credit from victim sources, 98% of the funds were immediately dispersed in chunks between ₹9,750 and ₹9,950 to 14 mule accounts during nocturnal hours (2 AM). Structuring transactions just below ₹10,000 avoids mandatory reporting. Strong correlation with Fan-out Dispersal Ring RING_FO_01.",
    ring_id: "RING_FO_01",
    computed_at: "2026-09-29T12:00:00Z",
  },
  ACC_00108: {
    account_id: "ACC_00108",
    score: 96,
    top_features: {
      band: "high",
      shap: [
        {
          feature: "in_short_cycle",
          value: 1.0,
          direction: "increases_risk",
          contribution: 0.38,
          description: "participates in circular money flow (A→B→C→D→A loop)",
        },
        {
          feature: "clustering_coef",
          value: 0.78,
          direction: "increases_risk",
          contribution: 0.25,
          description: "forms tightly coupled closed transaction loop",
        },
        {
          feature: "median_dwell_minutes",
          value: 22,
          direction: "increases_risk",
          contribution: 0.20,
          description: "holds capital for an average of only 22 minutes",
        },
        {
          feature: "amount_cv",
          value: 0.12,
          direction: "increases_risk",
          contribution: 0.15,
          description: "highly uniform circular transfers (₹35k - ₹48k)",
        },
      ],
    },
    explanation_text:
      "HIGH CONFIDENCE FRAUD RING: Account ACC_00108 is a core nexus in a multi-hop circular layering ring. Transactions form closed directed cycles spanning 5 accounts across ICICI, Axis, and Kotak with an average retention window under 25 minutes. Primary objective is obfuscating transaction lineage and confusing banking tracing algorithms.",
    ring_id: "RING_CL_02",
    computed_at: "2026-09-29T11:45:00Z",
  },
  ACC_00215: {
    account_id: "ACC_00215",
    score: 97,
    top_features: {
      band: "high",
      shap: [
        {
          feature: "max_accounts_per_device",
          value: 10,
          direction: "increases_risk",
          contribution: 0.42,
          description: "device DEV_FARM_9921 is shared across 10 distinct accounts",
        },
        {
          feature: "max_txn_10min",
          value: 18,
          direction: "increases_risk",
          contribution: 0.29,
          description: "peak velocity of 18 transactions within 10 minutes",
        },
        {
          feature: "account_age_days",
          value: 8,
          direction: "increases_risk",
          contribution: 0.22,
          description: "account created only 8 days ago in coordinated batch",
        },
      ],
    },
    explanation_text:
      "DEVICE FARM SYNDICATE: Account ACC_00215 shares exact physical hardware telemetry (DEV_FARM_9921) with 9 other accounts all registered within a 48-hour window. Velocity profile displays automated scripting with near-threshold transfers executed between 3 AM and 4 AM.",
    ring_id: "RING_DF_03",
    computed_at: "2026-09-29T11:50:00Z",
  },
  ACC_00001: {
    account_id: "ACC_00001",
    score: 12,
    top_features: {
      band: "low",
      shap: [
        {
          feature: "account_age_days",
          value: 720,
          direction: "decreases_risk",
          contribution: -0.35,
          description: "mature account history (>2 years established)",
        },
        {
          feature: "fan_in",
          value: 1,
          direction: "decreases_risk",
          contribution: -0.22,
          description: "single predictable regular payroll credit source",
        },
        {
          feature: "night_txn_ratio",
          value: 0.02,
          direction: "decreases_risk",
          contribution: -0.18,
          description: "normal diurnal transactions during standard hours",
        },
      ],
    },
    explanation_text:
      "VERIFIED BENIGN ACCOUNT: Consistent salaried profile with regular payroll inbound credits, high dwell time, and routine domestic retail merchant payments. No association with detected fraud clusters.",
    ring_id: null,
    computed_at: "2026-09-29T10:15:00Z",
  },
};

// Mock Fraud Rings
export const MOCK_RINGS: FraudRing[] = [
  {
    ring_id: "RING_FO_01",
    name: "Operation Garuda — Nocturnal Fan-Out Ring",
    archetype: "fan_out_dispersal",
    member_account_ids: [
      "ACC_00042",
      "ACC_00043",
      "ACC_00044",
      "ACC_00045",
      "ACC_00046",
      "ACC_00047",
      "ACC_00048",
      "ACC_00049",
      "ACC_00050",
      "ACC_00051",
      "ACC_00052",
      "ACC_00053",
    ],
    total_flow_amount: 4250000,
    detection_method: "Temporal Burst & Fan-out Ratio > 10",
    detected_at: "2026-09-28T03:30:00Z",
    risk_score: 96,
    summary:
      "1 primary funnel account (ACC_00042) received ₹4.5L bulk fraud loot and rapidly dispersed ₹9,800-₹9,950 structured amounts across 11 satellite mules within 35 minutes to evade reporting thresholds.",
    nodes: [
      { id: "ACC_00042", label: "ACC_00042 (Source)", type: "account", role: "source", risk_score: 94, bank: "SBI", status: "flagged", x: 400, y: 220 },
      { id: "ACC_00043", label: "ACC_00043 (Mule 1)", type: "account", role: "mule", risk_score: 89, bank: "HDFC", status: "flagged", x: 220, y: 100 },
      { id: "ACC_00044", label: "ACC_00044 (Mule 2)", type: "account", role: "mule", risk_score: 91, bank: "PNB", status: "on_hold", x: 340, y: 70 },
      { id: "ACC_00045", label: "ACC_00045 (Mule 3)", type: "account", role: "mule", risk_score: 86, bank: "SBI", status: "flagged", x: 470, y: 70 },
      { id: "ACC_00046", label: "ACC_00046 (Mule 4)", type: "account", role: "mule", risk_score: 88, bank: "ICICI", status: "flagged", x: 590, y: 110 },
      { id: "ACC_00047", label: "ACC_00047 (Mule 5)", type: "account", role: "mule", risk_score: 90, bank: "Axis", status: "flagged", x: 630, y: 220 },
      { id: "ACC_00048", label: "ACC_00048 (Mule 6)", type: "account", role: "mule", risk_score: 85, bank: "Kotak", status: "flagged", x: 600, y: 330 },
      { id: "ACC_00049", label: "ACC_00049 (Mule 7)", type: "account", role: "mule", risk_score: 87, bank: "HDFC", status: "flagged", x: 470, y: 370 },
      { id: "ACC_00050", label: "ACC_00050 (Mule 8)", type: "account", role: "mule", risk_score: 89, bank: "SBI", status: "flagged", x: 330, y: 370 },
      { id: "ACC_00051", label: "ACC_00051 (Mule 9)", type: "account", role: "mule", risk_score: 84, bank: "PNB", status: "flagged", x: 210, y: 320 },
      { id: "ACC_00052", label: "ACC_00052 (Mule 10)", type: "account", role: "mule", risk_score: 87, bank: "Axis", status: "flagged", x: 170, y: 210 },
    ],
    edges: [
      { id: "E1", source: "ACC_00042", target: "ACC_00043", amount: 9950, count: 3, is_suspicious: true },
      { id: "E2", source: "ACC_00042", target: "ACC_00044", amount: 9800, count: 2, is_suspicious: true },
      { id: "E3", source: "ACC_00042", target: "ACC_00045", amount: 9900, count: 3, is_suspicious: true },
      { id: "E4", source: "ACC_00042", target: "ACC_00046", amount: 9750, count: 2, is_suspicious: true },
      { id: "E5", source: "ACC_00042", target: "ACC_00047", amount: 9900, count: 4, is_suspicious: true },
      { id: "E6", source: "ACC_00042", target: "ACC_00048", amount: 9850, count: 2, is_suspicious: true },
      { id: "E7", source: "ACC_00042", target: "ACC_00049", amount: 9950, count: 3, is_suspicious: true },
      { id: "E8", source: "ACC_00042", target: "ACC_00050", amount: 9800, count: 3, is_suspicious: true },
      { id: "E9", source: "ACC_00042", target: "ACC_00051", amount: 9700, count: 2, is_suspicious: true },
      { id: "E10", source: "ACC_00042", target: "ACC_00052", amount: 9920, count: 3, is_suspicious: true },
    ],
  },
  {
    ring_id: "RING_CL_02",
    name: "Operation Chakra — Inter-Bank Circular Layering",
    archetype: "circular_layering",
    member_account_ids: ["ACC_00108", "ACC_00109", "ACC_00110", "ACC_00111", "ACC_00112"],
    total_flow_amount: 1890000,
    detection_method: "Johnson's Directed Cycle & Flow Ratio > 0.95",
    detected_at: "2026-09-27T19:10:00Z",
    risk_score: 95,
    summary:
      "Closed 5-hop circular loop (A→B→C→D→E→A) with uniform ₹35k-₹48k transfers spaced 15–40 minutes apart, systematically breaking audit trails before final offshore crypto on-ramp.",
    nodes: [
      { id: "ACC_00108", label: "ACC_00108 (ICICI)", type: "account", role: "hub", risk_score: 96, bank: "ICICI", status: "flagged", x: 400, y: 100 },
      { id: "ACC_00109", label: "ACC_00109 (Axis)", type: "account", role: "mule", risk_score: 93, bank: "Axis", status: "flagged", x: 580, y: 220 },
      { id: "ACC_00110", label: "ACC_00110 (Kotak)", type: "account", role: "mule", risk_score: 95, bank: "Kotak", status: "on_hold", x: 500, y: 380 },
      { id: "ACC_00111", label: "ACC_00111 (HDFC)", type: "account", role: "mule", risk_score: 91, bank: "HDFC", status: "flagged", x: 300, y: 380 },
      { id: "ACC_00112", label: "ACC_00112 (SBI)", type: "account", role: "mule", risk_score: 94, bank: "SBI", status: "flagged", x: 220, y: 220 },
    ],
    edges: [
      { id: "CL1", source: "ACC_00108", target: "ACC_00109", amount: 48500, count: 5, is_suspicious: true },
      { id: "CL2", source: "ACC_00109", target: "ACC_00110", amount: 47000, count: 5, is_suspicious: true },
      { id: "CL3", source: "ACC_00110", target: "ACC_00111", amount: 46200, count: 4, is_suspicious: true },
      { id: "CL4", source: "ACC_00111", target: "ACC_00112", amount: 45000, count: 4, is_suspicious: true },
      { id: "CL5", source: "ACC_00112", target: "ACC_00108", amount: 44100, count: 4, is_suspicious: true },
    ],
  },
  {
    ring_id: "RING_DF_03",
    name: "Operation Vyuh — Central Device Farm",
    archetype: "device_farm",
    member_account_ids: ["ACC_00215", "ACC_00216", "ACC_00217", "ACC_00218", "ACC_00219", "ACC_00220", "DEV_FARM_9921"],
    total_flow_amount: 2980000,
    detection_method: "Hardware Telemetry Match & Device Fingerprint Concurrency",
    detected_at: "2026-09-28T14:40:00Z",
    risk_score: 97,
    summary:
      "A single rooted Android emulator / physical farm hub (DEV_FARM_9921) concurrently orchestrates 10 UPI accounts opened within 48 hours, conducting synchronized micro-transactions.",
    nodes: [
      { id: "DEV_FARM_9921", label: "DEV_FARM_9921 (Rooted Android)", type: "device", role: "device", risk_score: 99, x: 400, y: 220 },
      { id: "ACC_00215", label: "ACC_00215 (SBI)", type: "account", role: "mule", risk_score: 97, bank: "SBI", status: "flagged", x: 230, y: 120 },
      { id: "ACC_00216", label: "ACC_00216 (HDFC)", type: "account", role: "mule", risk_score: 96, bank: "HDFC", status: "flagged", x: 400, y: 80 },
      { id: "ACC_00217", label: "ACC_00217 (ICICI)", type: "account", role: "mule", risk_score: 95, bank: "ICICI", status: "on_hold", x: 570, y: 120 },
      { id: "ACC_00218", label: "ACC_00218 (Axis)", type: "account", role: "mule", risk_score: 94, bank: "Axis", status: "flagged", x: 570, y: 320 },
      { id: "ACC_00219", label: "ACC_00219 (Kotak)", type: "account", role: "mule", risk_score: 92, bank: "Kotak", status: "flagged", x: 400, y: 360 },
      { id: "ACC_00220", label: "ACC_00220 (PNB)", type: "account", role: "mule", risk_score: 93, bank: "PNB", status: "flagged", x: 230, y: 320 },
    ],
    edges: [
      { id: "DF1", source: "ACC_00215", target: "DEV_FARM_9921", amount: 0, count: 32, is_suspicious: true },
      { id: "DF2", source: "ACC_00216", target: "DEV_FARM_9921", amount: 0, count: 28, is_suspicious: true },
      { id: "DF3", source: "ACC_00217", target: "DEV_FARM_9921", amount: 0, count: 30, is_suspicious: true },
      { id: "DF4", source: "ACC_00218", target: "DEV_FARM_9921", amount: 0, count: 25, is_suspicious: true },
      { id: "DF5", source: "ACC_00219", target: "DEV_FARM_9921", amount: 0, count: 22, is_suspicious: true },
      { id: "DF6", source: "ACC_00220", target: "DEV_FARM_9921", amount: 0, count: 27, is_suspicious: true },
    ],
  },
  {
    ring_id: "RING_BM_04",
    name: "Operation Tvarit — Sub-10k Structuring Burst",
    archetype: "burst_mule",
    member_account_ids: ["ACC_00411", "ACC_00412", "ACC_00413", "ACC_00414"],
    total_flow_amount: 1420000,
    detection_method: "Frequency Burst (< 2hr) & ₹9,000-₹9,999 Clustering",
    detected_at: "2026-09-29T02:00:00Z",
    risk_score: 93,
    summary:
      "Accounts under 15 days old undergoing sudden transaction bursts (40+ transactions in 90 minutes) calibrated precisely below ₹10,000 threshold to evade AML monitoring triggers.",
    nodes: [
      { id: "ACC_00411", label: "ACC_00411 (Kotak)", type: "account", role: "source", risk_score: 93, bank: "Kotak", status: "flagged", x: 300, y: 150 },
      { id: "ACC_00412", label: "ACC_00412 (SBI)", type: "account", role: "mule", risk_score: 90, bank: "SBI", status: "flagged", x: 500, y: 150 },
      { id: "ACC_00413", label: "ACC_00413 (HDFC)", type: "account", role: "mule", risk_score: 91, bank: "HDFC", status: "flagged", x: 300, y: 300 },
      { id: "ACC_00414", label: "ACC_00414 (Axis)", type: "account", role: "mule", risk_score: 89, bank: "Axis", status: "flagged", x: 500, y: 300 },
    ],
    edges: [
      { id: "BM1", source: "ACC_00411", target: "ACC_00412", amount: 9940, count: 12, is_suspicious: true },
      { id: "BM2", source: "ACC_00412", target: "ACC_00413", amount: 9880, count: 10, is_suspicious: true },
      { id: "BM3", source: "ACC_00413", target: "ACC_00414", amount: 9920, count: 11, is_suspicious: true },
    ],
  },
  {
    ring_id: "RING_FC_05",
    name: "Operation Sangam — Collector Cash-out Funnel",
    archetype: "fan_in_collector",
    member_account_ids: ["ACC_00330", "ACC_00331", "ACC_00332", "ACC_00333", "ACC_00334"],
    total_flow_amount: 3840000,
    detection_method: "High Fan-in to Single Consolidation Node",
    detected_at: "2026-09-28T22:15:00Z",
    risk_score: 92,
    summary:
      "Multiple satellite mules receive victim phishing deposits and funnel 100% of receipts to a central master merchant/collector account (ACC_00330) within 60 minutes.",
    nodes: [
      { id: "ACC_00330", label: "ACC_00330 (Collector)", type: "account", role: "collector", risk_score: 92, bank: "Axis", status: "flagged", x: 400, y: 220 },
      { id: "ACC_00331", label: "ACC_00331 (Feeder 1)", type: "account", role: "mule", risk_score: 87, bank: "PNB", status: "flagged", x: 220, y: 120 },
      { id: "ACC_00332", label: "ACC_00332 (Feeder 2)", type: "account", role: "mule", risk_score: 86, bank: "SBI", status: "flagged", x: 580, y: 120 },
      { id: "ACC_00333", label: "ACC_00333 (Feeder 3)", type: "account", role: "mule", risk_score: 89, bank: "HDFC", status: "flagged", x: 220, y: 320 },
      { id: "ACC_00334", label: "ACC_00334 (Feeder 4)", type: "account", role: "mule", risk_score: 88, bank: "ICICI", status: "flagged", x: 580, y: 320 },
    ],
    edges: [
      { id: "FC1", source: "ACC_00331", target: "ACC_00330", amount: 18500, count: 4, is_suspicious: true },
      { id: "FC2", source: "ACC_00332", target: "ACC_00330", amount: 19200, count: 4, is_suspicious: true },
      { id: "FC3", source: "ACC_00333", target: "ACC_00330", amount: 17800, count: 3, is_suspicious: true },
      { id: "FC4", source: "ACC_00334", target: "ACC_00330", amount: 19900, count: 5, is_suspicious: true },
    ],
  },
];

// Mock Active Holds Data
export const MOCK_HOLDS: HoldActionResponse[] = [
  {
    action_id: "ACT_HOLD_9001",
    account_id: "ACC_00044",
    officer_id: "OFF_MP_2026",
    reason: "Suspected Fan-out dispersal mule receiving structured payments under ₹10k from source ACC_00042",
    hold_start: "2026-09-18T10:00:00Z",
    hold_expiry: "2026-11-17T10:00:00Z", // ~49 days remaining
    status: "active",
  },
  {
    action_id: "ACT_HOLD_9002",
    account_id: "ACC_00110",
    officer_id: "OFF_MP_2026",
    reason: "Inter-bank circular layering node in Operation Chakra (Johnson cycle flow > ₹18L)",
    hold_start: "2026-09-02T14:30:00Z",
    hold_expiry: "2026-11-01T14:30:00Z", // ~33 days remaining
    status: "active",
  },
  {
    action_id: "ACT_HOLD_9003",
    account_id: "ACC_00217",
    officer_id: "OFF_DEL_2026",
    reason: "Device farm emulator linkage (DEV_FARM_9921) with 9 synchronized mule accounts",
    hold_start: "2026-09-24T09:15:00Z",
    hold_expiry: "2026-11-23T09:15:00Z", // ~55 days remaining
    status: "active",
  },
  {
    action_id: "ACT_HOLD_8890",
    account_id: "ACC_00889",
    officer_id: "OFF_MH_2026",
    reason: "Victim cyber-complaint portal report #1930-MH-2026-4410",
    hold_start: "2026-07-28T08:00:00Z",
    hold_expiry: "2026-09-26T08:00:00Z", // Expired 3 days ago!
    status: "active", // Ready to be processed by /actions/holds/expired!
  },
  {
    action_id: "ACT_HOLD_7712",
    account_id: "ACC_00771",
    officer_id: "OFF_MP_2026",
    reason: "Phishing funnel receiver; released after legitimate merchant audit documentation provided",
    hold_start: "2026-08-10T11:00:00Z",
    hold_expiry: "2026-10-09T11:00:00Z",
    status: "released",
  },
  {
    action_id: "ACT_HOLD_6601",
    account_id: "ACC_00660",
    officer_id: "OFF_CBI_2026",
    reason: "60-day statutory holding period concluded without federal indictment filing",
    hold_start: "2026-06-01T10:00:00Z",
    hold_expiry: "2026-07-31T10:00:00Z",
    status: "expired",
  },
];
